### ISSUE TITLE
Borders thinner on mobile

### ISSUE THREAD

**Issue by JoseRivas1998** [JoseRivas1998/SSHS-Redesign#175]
Do a media query in your css to make the borders smaller on smaller screens, would probably look better imo

**Comment by JoseRivas1998** [comment]
Here's an example of a media query
Lets just say that we have a p tag, and we want the text to be bigger on mobile.

``` css
p {
 font-size: 14px;
}
@media (max-width: 767px) {
 p {
  font-size:18px;
 }
}
```

Remember that CSS is read from top to bottom, so your media query must come after the original CSS.
