### ISSUE TITLE
Right Carousel Icon 50% from right always

### ISSUE THREAD

**Issue by JoseRivas1998** [JoseRivas1998/SSHS-Redesign#240]
## Internal or External Request

Internal
## Describe the request

Simple fix to the arrow sticking to the very far right on smaller screens.

``` CSS
.carousel-control > .fa.fa-arrow-right {
    right: 50%;
}
```
## Proposed Due Date

3-5-16
## Relevant Screenshots

Current and Incorrect
![image](https://cloud.githubusercontent.com/assets/6099936/13551616/701e7a42-e2f4-11e5-841b-d213ada4c2b6.png)

Prototyped Improvement
![image](https://cloud.githubusercontent.com/assets/6099936/13551617/788e3d34-e2f4-11e5-9eff-259deedbf191.png)
